### ISSUE TITLE
Bad command escaping

### ISSUE THREAD

**Issue by pahaz** [pahaz/bashtest#5]
```
$ python ../../bashtest.py -v *.bashtest
Trying:
    run('ls testsuit/')
Expecting:
    foo.py  main.py
ok
Trying:
    run('./stat.sh testsuit/')
Expecting:
    Evaluate *.py statistics
    PYTHON FILES:        2
    PYTHON LINES:        4
ok
Trying:
    run(./stat.sh)
Expecting:
    Evaluate *.py statistics
    PYTHON FILES:        3
    PYTHON LINES:        6
**********************************************************************
File "tests.bashtest", line 10, in tests.bashtest
Failed example:
    run(./stat.sh)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest tests.bashtest[2]>", line 1
        run(./stat.sh)
            ^
    SyntaxError: invalid syntax
**********************************************************************
1 items had failures:
   1 of   3 in tests.bashtest
3 tests in 1 items.
2 passed and 1 failed.
***Test Failed*** 1 failures.
```

**Comment by pahaz** [comment]
https://github.com/pahaz/bashtest/commit/0fc4d49c6fc832ba64dfa1dca74cb8a1ddf3752b
